/*
 * Generated by ISE 25.02.9.8732 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F265_6134();
extern void F267_6296();
extern void F265_6138();
extern void F268_6300();
extern void F270_6464();
extern void F268_6305();
extern void F351_3981();
extern void F316_5980();
extern void F132_1629();
extern EIF_REFERENCE F132_1616();
extern EIF_BOOLEAN F132_1628();
extern EIF_BOOLEAN F132_1636();
extern void F132_1638();
extern void F132_1639();
extern void F132_1640();
extern void F73_1287();
extern EIF_TYPED_VALUE F73_1288();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F265_6134;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F265_6138;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F268_6300;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F268_6305;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F351_3981;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F267_6296;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F270_6464;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F316_5980;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F132_1629;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F132_1628;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F132_1616;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F132_1636;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F132_1638;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F132_1639;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F132_1640;

	egc_str_dtype = 266;

	egc_immstr8_dtype = 265;

	egc_str32_dtype = 269;

	egc_immstr32_dtype = 268;
	egc_arr_dtype = 350;
	egc_tup_dtype = 218;
	egc_disp_rout_id = 2295;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x0204;
	egc_sp_wchar = 0x01E0;
	egc_sp_bool = 0x0385;
	egc_sp_uint8 = 0x0234;
	egc_sp_uint16 = 0x0361;
	egc_sp_uint32 = 0x0183;
	egc_sp_uint64 = 0x0257;
	egc_sp_int8 = 0x0319;
	egc_sp_int16 = 0x02F5;
	egc_sp_int32 = 0x01A7;
	egc_sp_int64 = 0x033D;
	egc_sp_real32 = 0x02AD;
	egc_sp_real64 = 0x02D1;
	egc_sp_pointer = 0x0296;
	egc_sp_ref = 0x0161;

	egc_uint8_dtype = 238;
	egc_uint16_dtype = 220;
	egc_uint32_dtype = 235;
	egc_uint64_dtype = 232;
	egc_int8_dtype = 229;
	egc_int16_dtype = 226;
	egc_int32_dtype = 223;
	egc_int64_dtype = 256;
	egc_bool_dtype = 253;
	egc_real32_dtype = 241;
	egc_char_dtype = 250;
	egc_wchar_dtype = 247;
	egc_real64_dtype = 244;
	egc_point_dtype = 259;

	egc_exception_dtype = 91;
	egc_except_emnger_dtype = 131;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "simple_scheduler";
	egc_system_location = "D:\\prod\\simple_scheduler\\EIFGENs\\simple_scheduler_tests\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1765680628;
	egc_has_old_special_semantic = 0;
	scount = 991;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "TEST_APP.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 723;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 2866;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 5221;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 72;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F73_1287;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F73_1288;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 29; /* TEST_APP */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 189; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 287; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
